#!/bin/sh

if [[ $(ps aux | grep "[i]Term.app") ]]; then
    echo "Please quit iTerm before running this script"
    exit
fi

script_path="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

cd ~

# ask for the administrator password upfront
sudo -v

# keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source "$script_path/utils"

# exit immediately on error
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e

# set the computer name
echo "Your computer name is \"$(hostname)\". Would you like to change it? (y/n)"
read -r response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  echo "What would you like it to be?"
  read computer_name
  sudo scutil --set ComputerName $computer_name
  sudo scutil --set HostName $computer_name
  sudo scutil --set LocalHostName $computer_name
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $computer_name
fi

# update (or clone) my dotfiles
fancy_echo "clone/update dotfiles"
if [ -d "$HOME/.dotfiles/" ]; then
  git -C $HOME/.dotfiles pull 
else
  git clone https://github.com/vbdjames/dotfiles.git ~/.dotfiles
fi

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

fancy_echo "clone/update antigen"
# pull down (or update) antigen
if [ -d "$HOME/.antigen/" ]; then
    git -C $HOME/.antigen pull
else
    git clone https://github.com/zsh-users/antigen.git ~/.antigen
fi

case "$SHELL" in
  */zsh) : ;;
  *)
    fancy_echo "Changing your shell to zsh ..."
      chsh -s "$(which zsh)"
    ;;
esac

source "$script_path/homebrew"
source "$script_path/dev-tools"
source "$script_path/ruby"
source "$script_path/python"
source "$script_path/java"
source "$script_path/node"
source "$script_path/scheme"
source "$script_path/macvim"
source "$script_path/apps"
source "$script_path/osx"
source "$script_path/iterm"
source "$script_path/text"

brew cleanup
brew linkapps

/bin/zsh -c "source ~/.zshrc && antigen update"

cat $script_path/post-install-msg

cd -
