#!/bin/sh
#
# http://stevelosh.com/blog/2012/10/the-homely-mutt/
#
if [ ! -d "$HOME/offlineimap/" ]; then
    git clone https://github.com/vbdjames/offlineimap.git ~/offlineimap
    cd ~/offlineimap
    git checkout 679c491c56c981961e18aa43b31955900491d7a3
    python setup.py install
fi

brew_install_or_upgrade sqlite

if [ ! -d "$HOME/.mail/" ]; then
    mkdir ~/.mail
fi

read -s -p "Enter GMail password (doug@vbdjames.com): " pword
security add-internet-password -a doug@vbdjames.com -s imap.gmail.com -r http -w $pword -U
security add-internet-password -a doug@vbdjames.com -s smtp.gmail.com -r smtp -w $pword -U


brew_tap sgeb/mutt
brew_install_or_upgrade sgeb/mutt/mutt --with-sidebar-patch

brew_install_or_update urlview
brew_install_or_update msmtp
brew_install_or_update contacts

curl -L https://bitbucket.org/sjl/dotfiles/raw/86bde83af492254c454db1ca99bf5feec0fa9532/bin/addcontact -o ~/.bin/addcontact && chmod +x ~/.bin/addcontact

brew_install_or_update notmuch

curl -L https://raw.githubusercontent.com/honza/mutt-notmuch-py/master/mutt-notmuch-py -o ~/.bin/mutt-notmuch-py && chmod +x ~/.bin/mutt-notmuch-py

# run offlineimap - maybe later, or put it in the post-install instructions - takes a long time!
# run notmuch new - later to do the initial index
